### ISSUE TITLE
Size getting clipped

### ISSUE THREAD

**Issue by nigelhamilton** [pascalpp/FreeRuler#85] opened 2020-07-23 08:57 UTC
![widthCutOff](https://user-images.githubusercontent.com/6199898/88268777-e1160c00-ccca-11ea-9e65-98885fd3b822.png)

**Comment by nigelhamilton** [comment] 2020-07-23 08:58
As you can see. the size measurement can be difficult to read as it is clipped slightly.

**Comment by pascalpp** [comment] 2020-07-23 13:35
Dupe of #84. Please download the latest release from Github. The App Store version is one version behind because of an app store rejection I still need to address.

**Closed by pascalpp** 2020-07-23 13:35 UTC
