### ISSUE TITLE
Does not have the conversion settings

### ISSUE THREAD

**Issue by vtstone** [pascalpp/FreeRuler#67] opened 2019-10-15 17:47 UTC
Hello,

I have been using the ruler for quite a while and enjoy using it. I am wondering the new version of the ruler will be available in inches instead of pixels and if it will have a conversion settings available like it did in the previous versions. It sucks that with the new Mac Catalina update, it doesn't allow for the old version to work. This ruler rocks!

**Comment by pascalpp** [comment] 2019-10-15 17:51
Thanks. I'm planning to add support for other units as time allows. Closing this as a duplicate of #68

**Closed by pascalpp** 2019-10-15 17:51 UTC

**Comment by vtstone** [comment] 2020-01-21 23:47
Hello,
Just checking in on this enhancement.

**Comment by fabulousrice** [comment] 2021-01-25 20:15
Checking in on the feature as well

**Comment by pascalpp** [comment] 2021-01-26 17:23
This is now available in https://github.com/pascalpp/FreeRuler/releases/tag/v2.0.4
