### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by SDS26** [pascalpp/FreeRuler#82] opened 2020-04-26 22:04 UTC
Hi Pascal,

   Just add all the features that were in previous versions-  like those found in Version 1.7b5.

Cheers,

Steve

**Comment by jeff-h** [comment] 2020-04-26 22:15
@SDS26 welcome to GitHub :) This new version of FreeRuler is a complete ground-up rebuild using modern technologies. It implicitly inherits nothing more than the name from the previous version.

So asking Pascal to "just add all the features" is by no means a trivial request and would involve tens if not hundreds of hours of time.

More useful would be to identify just one or two features from the previous version which you really truly miss on a daily basis and request those. Or even better learn Swift and offer a PR :)

**Comment by SDS26** [comment] 2020-04-27 20:34
Hi Jeff,
   Thanks for the reply.  The main feature that I miss is the units of measurement.
Cheers,
Steve


-----Original Message-----

**Comment by pascalpp** [comment] 2020-04-27 21:10
Duplicate of #68

**Closed by pascalpp** 2020-04-27 21:10 UTC
